export const cuisineList = [
  // "American",
  // "BBQ",
  // "Breakfast",
  // "Burgers",
  // "Cafe",
  // "Chinese",
  // "Desserts",
  // "French",
  // "Greek",
  // "Healthy",
  // "Indian",
  // "Italian",
  // "Japanese",
  // "Mexican",
  // "Noodles",
  // "Organic",
  // "Pasta",
  // "Pizza",
  // "Salads",
  // "Seafood",
  // "Spanish",
  // "Steak",
  // "Sushi",
  // "Tacos",
  // "Tapas",
  // "Vegan",

  // Indian cuisines
  "Indian",
  "Gujarati",
  "Punjabi",
  "North Indian",
  "South Indian",
  "Rajasthani",
  "Bengali",
  "Maharashtrian",
  "Kathiyawadi",
  "Andhra",
  "Chettinad",
  "Kashmiri",

  // Indian dishes
  "Biryani",
  "Tandoori",
  "Butter Chicken",
  "Samosa",
  "Chaat",
  "Dosa",
  "Idli",
  "Paneer",
  "Curry",
  "Naan",
  "Paratha",
  "Dal Makhani",
  "Vada Pav",
  "Pav Bhaji",
  "Bhakri",
  "Thepla",
  "Undhiyu",
  "Khaman",
  "Dhokla",
  "Handvo",
  "Misal Pav",
  "Sarson da Saag",
  "Makki di Roti",
  "Pindi Chole",
  "Rajma Chawal",
  "Litti Chokha",
  "Pesarattu",

  // International cuisines
  "Pizza",
  "Pasta",
  "French Fries",
  "Burgers",
  "BBQ",
  "Breakfast",
  "Chinese",
  "Japanese",
  "Greek",
  "Mexican",
  "Tacos",
  "Noodles",
  "Sushi",
  "Tapas",
  "Seafood",
  "Salads",
  "Organic",
  "Healthy",

  // Desserts and vegan options
  "Desserts",
  "Vegan",
  "Ice Cream",
  "Gulab Jamun",
  "Rasgulla",
  "Jalebi",
  "Rabri",
  "Laddu",
  "Halwa",
];
